Server:
  port: 8002


spring:
  application:
    name: cloud-consumer-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://rm-bp1b879u29h2125j1oo.mysql.rds.aliyuncs.com:3306/special_car?useUnicode=true&characterEncoding=UTF-8
    username: liyuli
    password: liyuli@2021


#eureka的配置補充
eureka:
  client:
    #表示是否將自己注冊进入EurekaServer 默认是true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认是true，单节点无所谓，集群必须设置为ture才能配合ribbon的负载均衡
    fetchRegistry: true
    service-url:
    #defaultZone: http://localhost:7001/eureka  单机版
    #集群版 都要注册上
    defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka


mybatis:
  type-aliases-package: com.atgugu.springcloud.entities