server:
  port: 8001

spring:
  application:
    name: cloud-payment-8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://rm-bp1b879u29h2125j1oo.mysql.rds.aliyuncs.com:3306/special_car?useUnicode=true&characterEncoding=UTF-8
    username: liyuli
    password: liyuli@2021


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities